server:
  port: 8440
spring:
  application:
    name: gateway-zuul-fallback
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8100/eureka
  instance:
    prefer-ip-address: true      #eureka服务地址
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: ALWAYS
##timeout config
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #超时时间根据自己项目需要设置
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000