spring:
  application:
    name: EUREKA-HA

---
server:
  port: 8261
spring:
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8262/eureka/

---
server:
  port: 8262
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8261/eureka/
