server:
  port: 8084
spring:
  application:
    name: ribbon-with-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8100/eureka #eureka服务地址
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true  #显示ip
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000   #用于测试Fallback方法
management:
  endpoint:
    health:
      show-details: always   #展示health详细信息
