server:
  port: 8170
spring:
  application:
    name: zuul-filter
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8100/eureka
  instance:
    prefer-ip-address: true
management:                       #显示路由zuul的端口配置，不配置无法访问 /routes
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
      health:
        show-details: ALWAYS
