server:
  port: 8083
spring:
  application:
    name: client-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8100/eureka #eureka服务地址
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true      #显示ip