server:
  port: 8284
spring:
  application:
    name: client-consumer-feign-customizing
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8100/eureka #eureka服务地址
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true      #显示ip
logging:
  level:
       com.example.eurekaconsumerclient.feign.TestClient: debug
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000      #解决超时问题（延长请求时间)
